### PR TITLE
Fix github action: `e2e.yml`

### PR DESCRIPTION
**Pull request by Zaubeerer**

### CODE REVIEW

**Review by bbelderbos — APPROVED** [review]
sweet thanks

**Comment by Zaubeerer** [comment]
The check did not succeed yet :S

**Comment by bbelderbos** [comment]
> The check did not succeed yet :S

It seems to hang? https://github.com/bbelderbos/decisions/actions/runs/4184697043/jobs/7252600363

**Comment by Zaubeerer** [comment]
Yeah, I am creating a new PR to further test.

**Pull request merged**
